const listaProductos= [
    {id:1,nombre:"COCACOLA",grupo:"gaseosa",precio:"599",stock:100,img:"./imagen/productos/cocacola_225l.png"},
    {id:2,nombre:"PEPSI",grupo:"gaseosa",precio:"467",stock:100,img:"./imagen/productos/pepsi_225l.png"},
    {id:3,nombre:"SPRITE",grupo:"gaseosa",precio:"449",stock:100,img:"./imagen/productos/sprite_225l.png"},
    {id:4,nombre:"FANTA",grupo:"gaseosa",precio:"450",stock:100,img:"./imagen/productos/fanta_225l.png"},
    {id:5,nombre:"QUILMES",grupo:"cerveza",precio:"550",stock:100,img:"./imagen/productos/quilmes.png"},
    {id:6,nombre:"ANDES",grupo:"cerveza",precio:"560",stock:100,img:"./imagen/productos/andes.png"},
    {id:7,nombre:"IMPERIAL",grupo:"cerveza",precio:"560",stock:100,img:"./imagen/productos/imperia.png"},
    {id:8,nombre:"HEINEKEN",grupo:"cerveza",precio:"680",stock:100,img:"./imagen/productos/heineken.png"},
    {id:9,nombre:"ALFAJOR AGUILA",grupo:"alfajor",precio:"200",stock:100,img:"./imagen/productos/aguila.png"},
    {id:10,nombre:"ALFAJOR TERRABUSI",grupo:"alfajor",precio:"200",stock:100,img:"./imagen/productos/terrabusi.png"},
    {id:11,nombre:"ALFAJOR SHOT",grupo:"alfajor",precio:"200",stock:100,img:"./imagen/productos/shot.png"},
    {id:12,nombre:"ALFAJOR PEPITO",grupo:"alfajor",precio:"200",stock:100,img:"./imagen/productos/pepito.png"},
    {id:13,nombre:"FIDEO MOÑITO",grupo:"pasta",precio:"180",stock:100,img:"./imagen/productos/fideo_monito.png"},
    {id:14,nombre:"FIDEO TIRABUZON",grupo:"pasta",precio:"220",stock:100,img:"./imagen/productos/fideo_tirabuzon.png"},
    {id:15,nombre:"FIDEO SPAGUETI",grupo:"pasta",precio:"150",stock:100,img:"./imagen/productos/fideo_spagueti.png"},
    {id:16,nombre:"RAVIOLES",grupo:"pasta",precio:"450",stock:100,img:"./imagen/productos/ravioles.png"},
    {id:17,nombre:"CHOCOLATE SNICKERS",grupo:"chocolate",precio:"310",stock:100,img:"./imagen/productos/snickers.png"},
    {id:18,nombre:"CHOCOLATE HERSHEYS",grupo:"chocolate",precio:"790",stock:100,img:"./imagen/productos/hersheys.png"},
    {id:19,nombre:"CHOCOLATE MILKA",grupo:"chocolate",precio:"420",stock:100,img:"./imagen/productos/milka.png"},
    {id:20,nombre:"CHOCOLATE BLOCK",grupo:"chocolate",precio:"380",stock:100,img:"./imagen/productos/block.png"}
]